package com.brainbrakers.medcalc;

public enum CompParams {
    NOT_USED,
    SKF_WEIGHT,
    IMT_HEIGHT,
    SKF_AGE,
    SKF_SEX,
    SKF_CREATININE,
    IMT_WEIGHT,
    BSA_HEIGHT,
    BSA_WEIGHT,
    CPK_HEMOGLOBIN,
    CPK_ERYTHROCYTES,
    CHA2DS2_HEART_FIBRILATION,
    CHA2DS2_HYPERTENSION,
    CHA2DS2_AGE75,
    CHA2DS2_DIABETES,
    CHA2DS2_STROKE,
    CHA2DS2_VASCULAR,
    CHA2DS2_AGE65,
    CHA2DS2_SEX_CATEGORY
}
