package com.brainbrakers.medcalc;

public enum CompParams {
    NOT_USED,
    SKF_WEIGHT,
    IMT_HEIGHT,
    SKF_AGE,
    SKF_SEX,
    SKF_CREATININE,
    IMT_WEIGHT,
    BSA_HEIGHT,
    BSA_WEIGHT,
    CPK_HEMOGLOBIN,
    CPK_ERYTHROCYTES,
    CHA2DS2_HEART_FIBRILATION,
    CHA2DS2_HYPERTENSION,
    CHA2DS2_AGE75,
    CHA2DS2_DIABETES,
    CHA2DS2_STROKE,
    CHA2DS2_VASCULAR,
    CHA2DS2_AGE65,
    CHA2DS2_SEX_CATEGORY,
    HASBLED_HYPERTENSION,
    HASBLED_ABNORMAL_LIVER_FUNCTION,
    HASBLED_ABNORMAL_RENAL_FUNCTION,
    HASBLED_STROKE,
    HASBLED_BLEEDING_HISTORY_OR_PREDISPOSITION,
    HASBLED_LABILE_INTERNATIONAL_NORMALIZED_RATIO,
    HASBLED_ELDERLY_65_YEARS,
    HASBLED_DRUGS_CONCOMITANTLY,
    HASBLED_ALCOHOL_CONCOMITANTLY,
    CHILDPUGH_ASCITES,
    CHILDPUGH_ENCEPHALOPATHY,
    CHILDPUGH_BILIRUBIN,
    CHILDPUGH_ALBUMIN,

    /**
     * Удлинение ПВ (сек.)
     */
    CHILDPUGH_INR
}
